// Generated by Wrangler on Sun Oct 13 2024 17:23:13 GMT+0900 (대한민국 표준시)
// by running `wrangler types`

interface Env {
	kv: KVNamespace;
	API_URL: "https://remix-hono-test.pages.dev/";
	DB: D1Database;
}
