DROP TABLE IF EXISTS Todos;
CREATE TABLE IF NOT EXISTS Todos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  completed INTEGER NOT NULL DEFAULT 0
);

INSERT INTO Todos (title) VALUES ("test");